---
- name: Récupérer les informations des services systemd
  service_facts:

- name: Afficher l'état des services de sécurité
  debug:
    msg: "{{ item }} : {{ ansible_facts.services[item + '.service'].state | default('absent') }}"
  loop:
    - ssh
    - ufw
    - fail2ban
    - auditd
    - apparmor
    - clamav-freshclam
  changed_when: false
