---
- name: Appliquer paramètres sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop:
    - { name: "kernel.randomize_va_space", value: "2" }
    - { name: "kernel.kptr_restrict", value: "2" }
    - { name: "kernel.dmesg_restrict", value: "1" }
    - { name: "net.ipv4.tcp_syncookies", value: "1" }
    - { name: "net.ipv4.conf.all.accept_redirects", value: "0" }
    - { name: "net.ipv4.conf.default.accept_redirects", value: "0" }
    - { name: "fs.protected_hardlinks", value: "1" }
    - { name: "fs.protected_symlinks", value: "1" }
