---
- name: Installer ClamAV
  apt:
    name:
      - clamav
      - clamav-daemon
    state: present

- name: Activer freshclam
  service:
    name: clamav-freshclam
    enabled: yes
    state: started
