---
- name: Installer OpenSSH
  apt:
    name: openssh-server
    state: present

- name: Configurer SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    backup: true
  loop:
    - { key: "Port", value: "{{ ssh_port }}" }
    - { key: "PermitRootLogin", value: "no" }
    - { key: "PermitEmptyPasswords", value: "no" }
    - { key: "MaxAuthTries", value: "3" }
    - { key: "X11Forwarding", value: "no" }
  notify: Restart ssh

- name: Valider SSH
  command: sshd -t
  changed_when: false
