---
- name: Installer UFW
  apt:
    name: ufw
    state: present

- name: Politique entrante
  ufw:
    direction: incoming
    policy: deny

- name: Politique sortante
  ufw:
    direction: outgoing
    policy: allow

- name: Autoriser ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ ufw_allowed_ports }}"

- name: Activer UFW
  ufw:
    state: enabled
