---
- name: Installer AppArmor
  apt:
    name:
      - apparmor
      - apparmor-utils
    state: present

- name: Activer AppArmor
  service:
    name: apparmor
    enabled: true
    state: started
