---
- name: Installer Fail2ban
  apt:
    name: fail2ban
    state: present

- name: Configurer Fail2ban
  copy:
    dest: /etc/fail2ban/jail.local
    backup: true
    content: |
      [DEFAULT]
      bantime = 1h
      findtime = 10m
      maxretry = 5
      backend = systemd

      [sshd]
      enabled = true
      port = {{ ssh_port }}
      logpath = %(sshd_log)s
  notify: Restart fail2ban
