---
- name: Installer auditd
  apt:
    name:
      - auditd
      - audispd-plugins
    state: present

- name: Règles auditd
  copy:
    dest: /etc/audit/rules.d/hardening.rules
    backup: true
    content: |
      -w /etc/passwd -p wa -k passwd_changes
      -w /etc/shadow -p wa -k shadow_changes
      -w /etc/sudoers -p wa -k sudoers_changes
      -w /etc/ssh/sshd_config -p wa -k sshd_config_changes
